development:
  adapter: postgresql
  encoding: unicode
  database: pwr_dev
  pool: 5
  username: dev
  password: dev

test:
  adapter: postgresql
  encoding: unicode
  database: pwr_test
  pool: 5
  username: dev
  password: dev

production:
  adapter: postgresql
  encoding: unicode
  database: pwr
  pool: 5
  username: dev
  password: dev
